<?php
/**
 * Created by PhpStorm.
 * User: win10
 * Date: 2018/8/27
 * Time: 14:28
 */

namespace app\Common\Controller;


use think\Controller;

/**
 * Base基类控制器
 * Class Base
 * @package app\Common\Controller
 */
class Base extends Controller
{
    /**
     *  初始化方法
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 新增数据（添加）
     * @param Request $request
     * @return \think\response\Json
     */
    public function doAdd(Request $request){
        $param = $request->param();

        $controller = $request->controller();
        $model = model($controller);
        $result = $model->createData($param,'add');

        return $result;

//        if($result === true){                    //前后端分离
//            $ret = [
//                'code' => 200,
//                'msg' => '添加成功'
//            ];
//        }else{
//            $ret = [
//                'code' => 1001,
//                'msg' => $result
//            ];
//        }
//        return json($ret);
    }

    /**
     * 更新数据（修改）
     * @param Request $request
     * @return \think\response\Json
     */
    public function update(Request $request){
        $id = $request->param('id');       //当前更新对象的id
        $param = $request->except('id');   //获取出id之外的所有字段
        $param['user_id'] = session('Uid');

        $controller = $request->controller();
        $model = model($controller);
        $result = $model->updateDataById($param,$id,'update');

        return $result;

//        if($result === true){                     //前后端分离
//            $ret = [
//                'code' => 200,
//                'msg' => '编辑成功'
//            ];
//        }else{
//            $ret = [
//                'code' => 1001,
//                'msg' => $result
//            ];
//        }
//        return json($ret);
    }

    /**
     * 通过主键id查询数据
     * @param Request $request
     * @return \think\response\Json
     */
    public function getDataById(Request $request){
//        $ret = [                             //前后端分离
//            'code' => 1001,
//            'msg' => '暂无此数据'
//        ];

        $id = $request->param('id');
        $controller = $request->controller();
        $model = model($controller);
        $data = $model->getDataById($id);

        return $data;

//        if($data){                              //前后端分离
//            $ret = [
//                'code' => 200,
//                'msg' => 'success',
//                'data' => $data
//            ];
//        }
//        return json($ret);
    }

    /**
     * 通过主键id删除数据
     * @param Request $request
     * @return \think\response\Json
     */
    public function delDataById(Request $request){
//        $ret = [                        //前后端分离
//            'code' => 1001,
//            'msg' => '删除失败'
//        ];

        $id = $request->param('id');
        $controller = $request->controller();
        $model = model($controller);
        $result = $model->delDataById($id);

        return $result;

//        if($result){                       //前后端分离
//            $ret = [
//                'code' => 200,
//                'msg' => '删除成功'
//            ];
//        }
//        return json($ret);
    }

}