<?php
/**
 * Created by PhpStorm.
 * User: win10
 * Date: 2018/8/27
 * Time: 14:29
 */

namespace app\Common\Controller;

/**
 * Home基类控制器
 * Class Home
 * @package app\Common\Controller
 */
class Home extends Base
{
    /**
     *  初始化方法
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }



}